# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WeeeZLpQOnhCuJQ4X6oLaGMpyo-8bDt9
"""

#1
a = float(input("Enter the length of the rectangle:"))
b = float(input("Enter the width of the rectangle:"))
c = float(a*b)
print("The area of the rectangle is",c)

#2
weight = (float(input("Enter Weight in KG : ")))
height = (float(input("Enter Height in Metres : ")))
BMI = float(weight/height ** 2)
print("Your BMI is",BMI)

#3
dict = {}
a = input("Enter the name of the student:")
b = input("Enter the score of the student:")
dict[a]=b
print({a,b})

#4
a = int(input("Enter your age:"))
if a <= 0:
  print("Invalid Age, Please Enter a valid Age")
elif a < 18:
  print("You are a Minor")
elif a >=18 and a <= 50:
  print("You are a Major!")
else:
  print("You are a Senior!")

#5
for i in range(1,50,2):
  print(i)

#6
a = (input("Enter password - "))
if len(a) < 8:
  print("The password must contain 8 characters")
elif a not in a.lower():
  print("Atleast one small letter is required")
elif a not in a.upper():
  print("Atleast one capital letter is required")
else:
  print("Password is Updated!")

#7
def average(lst):
    total = 0
    for num in lst:
        total += num
    return total / len(lst)

my_list = [15, 9, 55, 41, 35, 20, 62, 49]
avg = average(my_list)
print(f"Average of the list: {avg:.2f}")

#8
def count_vowels(string):
    vowels = "AEIOUaeiou"
    return len([char for char in string if char in vowels])
string = "Hello, how are you?"
tot_vowels = count_vowels(string)
print(f"Total number of vowels in the string: {tot_vowels}")

#9
from datetime import datetime
now = datetime.now()
print(f"Current date and time: {now}")

#10
try:
    a = float(input("Enter num1:"))
    b = float(input("Enter num2:"))
    c = float(a + b)
    print(result)
except ValueError:
    print("Only numbers is expected in input")

#11
def func(a):
  try:
    a = float(input("Enter number:"))
    print("The number is",a)
  except ValueError:
    print("Only numbers is expected in input")
result = func(a)
print(result)

#12
try:
  a = int(input("Enter numerator:"))
  b = int(input("Enter denominator:"))
  c = a / b
  print("The answer is",c)
except ZeroDivisionError:
  print("Denominator cannot be 0.")

#13
vFP_text_file = open('/content/sample_data/a.txt','w')
a = "Hello, Python!"
vFP_text_file.writelines(a)
vFP_text_file.close()

#14
vFP_my_file = open('/content/sample_data/a.txt', 'r')
print(vFP_my_file.read())
vFP_my_file.close()

#15
vFP_text_file = open('/content/sample_data/a.txt','w')
a = "Enjoy Learning Python!"
vFP_text_file.writelines(a)
vFP_text_file.close()

"""# New section

# New section
"""

