# -*- coding: utf-8 -*-
"""LVADSUSR93_Keerthanaa_Lab_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o3irSMXVdAVTenpwGrF6Xg7QkAB8y3Mz
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,classification_report, confusion_matrix

df = pd.read_csv('/content/loan_approval.csv')
data = pd.DataFrame(df)
data

data.isnull().sum()

data.shape

plt.figure(figsize=(10,8))
sns.boxplot(data=data)
plt.title('Finding outliers')
plt.show()

q1 = data.quantile(0.25)
q3 = data.quantile(0.75)
iqr = q3 - q1

outliers = ((data < (q1 - 1.5 * iqr)) | (data > (q3 + 1.5 * iqr))).any(axis=1)
print(outliers)

cleaned_data = data[~outliers]
cleaned_data.shape

plt.figure(figsize=(10,8))
sns.boxplot(data=cleaned_data)
plt.title('After cleaning outliers')
plt.show()

df.info()

data1 = pd.get_dummies(cleaned_data, columns=[' education', ' self_employed'])

data1.head()

X = data1.drop(columns=[' loan_status'])
y = data1[' loan_status']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(data1.describe())

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:",mse)
print("R-squared:", r2_score(y_test, y_pred))